// @river/runtime — wiring for applications: store driver, projectors, assistant, demo seed.
export { surfaces } from './types/Surface.ts';
export type { Surface } from './types/Surface.ts';
export type { RuntimeConfig } from './types/RuntimeConfig.ts';
export type { Runtime } from './types/Runtime.ts';
export { readConfig } from './readConfig.ts';
export { allProjectors } from './allProjectors.ts';
export { publicActor } from './publicActor.ts';
export { commandEnv } from './commandEnv.ts';
export { createAssistant } from './createAssistant.ts';
export { seedDemo } from './seedDemo.ts';
export { resetDemo } from './resetDemo.ts';
export { loadSettings } from './loadSettings.ts';
export { personaIds } from './types/PersonaId.ts';
export type { PersonaId } from './types/PersonaId.ts';
export type { Persona } from './types/Persona.ts';
export type { DemoVariant, DemoCost } from './types/DemoVariant.ts';
export { findPersona } from './findPersona.ts';
export { listPersonas } from './listPersonas.ts';
export { personaName } from './personaName.ts';
export { personaIdentity } from './personaIdentity.ts';
export { identityActor } from './identityActor.ts';
export { getRuntime } from './getRuntime.ts';
