// @river/settings — the settings registry, profiles and resolution (adr/records/ADR-0020).
export { profileIds } from './types/ProfileId.ts';
export type { ProfileId } from './types/ProfileId.ts';
export type { ProfileTexts, ChannelEntry, ReferralEntry, DropOffEntry, PartnerEntry } from './types/ProfileTexts.ts';
export { settingKinds } from './types/SettingKind.ts';
export type { SettingKind } from './types/SettingKind.ts';
export type { SettingValue, EntryValue } from './types/SettingValue.ts';
export { settingGroups } from './types/SettingGroup.ts';
export type { SettingGroup } from './types/SettingGroup.ts';
export type { SettingChoice } from './types/SettingChoice.ts';
export type { EntryField } from './types/EntryField.ts';
export type { SettingDefinition } from './types/SettingDefinition.ts';
export type { Profile } from './types/Profile.ts';
export type { SettingsSnapshot, SettingSource } from './types/SettingsSnapshot.ts';
export { findSettingDefinition } from './findSettingDefinition.ts';
export { listSettingDefinitions } from './listSettingDefinitions.ts';
export { findProfile } from './findProfile.ts';
export { listProfiles } from './listProfiles.ts';
export { resolveSettings } from './resolveSettings.ts';
export { validateSettingValue } from './validateSettingValue.ts';
export { contrastRatio } from './contrastRatio.ts';
export { accentShades } from './accentShades.ts';
export { settingText } from './settingText.ts';
export { settingLocalised } from './settingLocalised.ts';
export { settingNumber } from './settingNumber.ts';
export { settingBoolean } from './settingBoolean.ts';
export { settingList } from './settingList.ts';
export { settingEntries } from './settingEntries.ts';
export { settingTokens } from './settingTokens.ts';
export { readSettingFromForm } from './readSettingFromForm.ts';
